const items = `
[
  {   "name": "common debug item",
      "lore": "A debug item for testing",
      "image": "Assets/textures/minecraft/potato.png",
      "stats": {
        "attack_damage": 0,
        "health": 0,
        "defense": 0,
        "strength": 0,
        "intelligence": 0,
        "crit_chance": 0,
        "crit_damage": 0,
        "bonus_attack_speed": 0,
        "ability_damage": 0,
        "true_defence": 0,
        "ferocity": 0,
        "health_regen": 0,
        "vitality": 0,
        "mending": 0,
        "swing_range": 0,
        "rarity": "common",
        "enchant_types": [],
        "reforge_types": []
      }
  },
  {   "name": "legendary debug item",
      "lore": "A debug item for testing",
      "image": "Assets/textures/minecraft/potato.png",
      "stats": {
        "attack_damage": 0,
        "health": 0,
        "defense": 0,
        "strength": 0,
        "intelligence": 0,
        "crit_chance": 0,
        "crit_damage": 0,
        "bonus_attack_speed": 0,
        "ability_damage": 0,
        "true_defence": 0,
        "ferocity": 0,
        "health_regen": 0,
        "vitality": 0,
        "mending": 0,
        "swing_range": 0,
        "rarity": "legendary",
        "enchant_types": [],
        "reforge_types": []
      }
  },
  {   "name": "Diamond Sword",
      "lore": "",
      "image": "Assets/textures/minecraft/diamond_sword.png",
      "stats": {
        "attack_damage": 35,
        "health": 0,
        "defense": 0,
        "strength": 0,
        "intelligence": 0,
        "crit_chance": 0,
        "crit_damage": 0,
        "bonus_attack_speed": 0,
        "ability_damage": 0,
        "true_defence": 0,
        "ferocity": 0,
        "health_regen": 0,
        "vitality": 0,
        "mending": 0,
        "swing_range": 0,
        "rarity": "common",
        "enchant_types": ["Sword"],
        "reforge_types": ["Sword"]
      }
  },
  {   "name": "Wooden Sword",
      "lore": "",
      "image": "Assets/textures/minecraft/wooden_sword.png",
      "stats": {
        "attack_damage": 7,
        "health": 0,
        "defense": 0,
        "strength": 0,
        "intelligence": 0,
        "crit_chance": 0,
        "crit_damage": 0,
        "bonus_attack_speed": 0,
        "ability_damage": 0,
        "true_defence": 0,
        "ferocity": 0,
        "health_regen": 0,
        "vitality": 0,
        "mending": 0,
        "swing_range": 0,
        "rarity": "common",
        "enchant_types": [],
        "reforge_types": []
      }
  },
  {   "name": "Iron Sword",
      "lore": "",
      "image": "Assets/textures/minecraft/iron_sword.png",
      "stats": {
        "attack_damage": 7,
        "health": 0,
        "defense": 0,
        "strength": 0,
        "intelligence": 0,
        "crit_chance": 0,
        "crit_damage": 0,
        "bonus_attack_speed": 0,
        "ability_damage": 0,
        "true_defence": 0,
        "ferocity": 0,
        "health_regen": 0,
        "vitality": 0,
        "mending": 0,
        "swing_range": 0,
        "rarity": "common",
        "enchant_types": [],
        "reforge_types": []
      }
  },
  {   "name": "Stone Sword",
      "lore": "",
      "image": "Assets/textures/minecraft/stone_sword.png",
      "stats": {
        "attack_damage": 7,
        "health": 0,
        "defense": 0,
        "strength": 0,
        "intelligence": 0,
        "crit_chance": 0,
        "crit_damage": 0,
        "bonus_attack_speed": 0,
        "ability_damage": 0,
        "true_defence": 0,
        "ferocity": 0,
        "health_regen": 0,
        "vitality": 0,
        "mending": 0,
        "swing_range": 0,
        "rarity": "common",
        "enchant_types": [],
        "reforge_types": []
      }
  },
  {   "name": "Golden Sword",
      "lore": "",
      "image": "Assets/textures/minecraft/golden_sword.png",
      "stats": {
        "attack_damage": 7,
        "health": 0,
        "defense": 0,
        "strength": 0,
        "intelligence": 0,
        "crit_chance": 0,
        "crit_damage": 0,
        "bonus_attack_speed": 0,
        "ability_damage": 0,
        "true_defence": 0,
        "ferocity": 0,
        "health_regen": 0,
        "vitality": 0,
        "mending": 0,
        "swing_range": 0,
        "rarity": "common",
        "enchant_types": ["Sword"],
        "reforge_types": []
      }
  },
  {   "name": "Prismarine Blade",
      "lore": "Deals <span style="color:green">+200%</span> damage while in water.",
      "image": "Assets/textures/minecraft/prismarine_blade.png",
      "stats": {
        "attack_damage": 50,
        "health": 0,
        "defense": 0,
        "strength": 25,
        "intelligence": 0,
        "crit_chance": 0,
        "crit_damage": 0,
        "bonus_attack_speed": 0,
        "ability_damage": 0,
        "true_defence": 0,
        "ferocity": 0,
        "health_regen": 0,
        "vitality": 0,
        "mending": 0,
        "swing_range": 0,
        "rarity": "uncommon",
        "enchant_types": ["sword"],
        "reforge_types": ["sword"]
      }
  }
]`

/*
base item

{   "name": "item",
      "lore": "itemLore",
      "image": "Assets/textures/minecraft/img.png",
      "stats": {
        "Damage": 0,
        "Strength": 0,
        "Health": 0,
        "Defense": 0,
        "Speed": 0,
        "Intelligence": 0,
        "Crit Chance": 0,
        "Crit Damage": 0,
        "Bonus Attack Speed": 0,
        "Ability Damage": 0,
        "True Defense": 0,
        "Ferocity": 0,
        "Health Regen": 0,
        "Vitality": 0,
        "Mending": 0,
        "Swing Range": 0,
        "Magic Find": 0,
        "Pet Luck": 0,
        "Sea Creature Chance": 0,
        "Double Hook Chance": 0,
        "Fishing Speed": 0,
        "Cold Resistance": 0,
        "Heat Resistance": 0,
        "Bonus Pest Chance": 0,
        "Mining Speed": 0,
        "Mining Spread": 0,
        "Gemstone Spread": 0,
        "Mining Fortune": 0,
        "Ore Fortune": 0,
        "Block Fortune": 0,
        "Dwarven Metal Fortune": 0,
        "Gemstone Fortune": 0,
        "Farming Fortune": 0,
        "Foraging Fortune": 0,
        "Pristine": 0,
        "Alchemy Wisdom": 0,
        "Carpentry Wisdom": 0,
        "Combat Wisdom": 0,
        "Enchanting Wisdom": 0,
        "Farming Wisdom": 0,
        "Fishing Wisdom": 0,
        "Foraging Wisdom": 0,
        "Mining Wisdom": 0,
        "Runecrafting Wisdom": 0,
        "Social Wisdom": 0,
        "Taming Wisdom": 0,
      }
        "rarity": "",
        "enchant_types": [],
        "reforge_types": []
      
  }
*/
