// this may look like an error, but i just made github think this file is a json so i can find errors more easily
const items = `
[
  {   "name": "Diamond Sword",
      "lore": "The well known minecraft sword",
      "image": "Assets/textures/minecraft/diamond_sword.png",
      "stats": {
        "attack_damage": "7",
        "health": "0",
        "defense": "0",
        "strength": "0",
        "intelligence": "0",
        "crit_chance": "0",
        "crit_damage": "0",
        "bonus_attack_speed": "0",
        "ability_damage": "0",
        "true_defence": "0",
        "ferocity": "0",
        "health_regen": "0",
        "vitality": "0",
        "mending": "0",
        "swing_range": "0",
        "rarity": "0-8",
        "enchant_types": [],
        "reforge_types": []
      }
  },
  {   "name": "Wooden Sword",
      "lore": "",
      "image": "Assets/textures/minecraft/wooden_sword.png",
      "stats": {
        "attack_damage": "7",
        "health": "0",
        "defense": "0",
        "strength": "0",
        "intelligence": "0",
        "crit_chance": "0",
        "crit_damage": "0",
        "bonus_attack_speed": "0",
        "ability_damage": "0",
        "true_defence": "0",
        "ferocity": "0",
        "health_regen": "0",
        "vitality": "0",
        "mending": "0",
        "swing_range": "0",
        "rarity": "0-8",
        "enchant_types": [],
        "reforge_types": []
      }
  },
  {   "name": "Iron Sword",
      "lore": "",
      "image": "Assets/textures/minecraft/iron_sword.png",
      "stats": {
        "attack_damage": "7",
        "health": "0",
        "defense": "0",
        "strength": "0",
        "intelligence": "0",
        "crit_chance": "0",
        "crit_damage": "0",
        "bonus_attack_speed": "0",
        "ability_damage": "0",
        "true_defence": "0",
        "ferocity": "0",
        "health_regen": "0",
        "vitality": "0",
        "mending": "0",
        "swing_range": "0",
        "rarity": "0-8",
        "enchant_types": [],
        "reforge_types": []
      }
  },
  {   "name": "Stone Sword",
      "lore": "",
      "image": "Assets/textures/minecraft/stone_sword.png",
      "stats": {
        "attack_damage": "7",
        "health": "0",
        "defense": "0",
        "strength": "0",
        "intelligence": "0",
        "crit_chance": "0",
        "crit_damage": "0",
        "bonus_attack_speed": "0",
        "ability_damage": "0",
        "true_defence": "0",
        "ferocity": "0",
        "health_regen": "0",
        "vitality": "0",
        "mending": "0",
        "swing_range": "0",
        "rarity": "0-8",
        "enchant_types": [],
        "reforge_types": []
      }
  },
  {   "name": "Golden Sword",
      "lore": "",
      "image": "Assets/textures/minecraft/golden_sword.png",
      "stats": {
        "attack_damage": "7",
        "health": "0",
        "defense": "0",
        "strength": "0",
        "intelligence": "0",
        "crit_chance": "0",
        "crit_damage": "0",
        "bonus_attack_speed": "0",
        "ability_damage": "0",
        "true_defence": "0",
        "ferocity": "0",
        "health_regen": "0",
        "vitality": "0",
        "mending": "0",
        "swing_range": "0",
        "rarity": "0-8",
        "enchant_types": [],
        "reforge_types": []
      }
  },
  {   "name": "Prismarine Blade",
      "lore": "",
      "image": "Assets/textures/item/weapons/normal/melee/prismarine_blade/prismarine_blade.png",
      "stats": {
        "attack_damage": "7",
        "health": "0",
        "defense": "0",
        "strength": "0",
        "intelligence": "0",
        "crit_chance": "0",
        "crit_damage": "0",
        "bonus_attack_speed": "0",
        "ability_damage": "0",
        "true_defence": "0",
        "ferocity": "0",
        "health_regen": "0",
        "vitality": "0",
        "mending": "0",
        "swing_range": "0",
        "rarity": "0-8",
        "enchant_types": [],
        "reforge_types": []
      }
  }
]`

/*
base item

{   "name": "item",
      "lore": "itemLore",
      "image": "direction/to/img.png",
      "stats": {
        "health": "0",
        "defense": "0",
        "strength": "0",
        "intelligence": "0",
        "crit_chance": "0",
        "crit_damage": "0",
        "bonus_attack_speed": "0",
        "ability_damage": "0",
        "true_defence": "0",
        "ferocity": "0",
        "health_regen": "0",
        "vitality": "0",
        "mending": "0",
        "swing_range": "0",
        "rarity": "0-8",
        "enchant_types": [],
        "reforge_types": []
      }
  }
*/
