const items = `
[
  {   "name": "common debug item",
      "lore": "A debug item for testing",
      "image": "Assets/textures/minecraft/potato.png",
      "stats": {
        "attack_damage": 0,
        "health": 0,
        "defense": 0,
        "strength": 0,
        "intelligence": 0,
        "crit_chance": 0,
        "crit_damage": 0,
        "bonus_attack_speed": 0,
        "ability_damage": 0,
        "true_defence": 0,
        "ferocity": 0,
        "health_regen": 0,
        "vitality": 0,
        "mending": 0,
        "swing_range": 0,
        "rarity": "common",
        "enchant_types": [],
        "reforge_types": []
      }
  },
  {   "name": "legendary debug item",
      "lore": "A debug item for testing",
      "image": "Assets/textures/minecraft/potato.png",
      "stats": {
        "attack_damage": 0,
        "health": 0,
        "defense": 0,
        "strength": 0,
        "intelligence": 0,
        "crit_chance": 0,
        "crit_damage": 0,
        "bonus_attack_speed": 0,
        "ability_damage": 0,
        "true_defence": 0,
        "ferocity": 0,
        "health_regen": 0,
        "vitality": 0,
        "mending": 0,
        "swing_range": 0,
        "rarity": "legendary",
        "enchant_types": [],
        "reforge_types": []
      }
  },
  {   "name": "Diamond Sword",
      "lore": "The well known minecraft sword",
      "image": "Assets/textures/minecraft/diamond_sword.png",
      "stats": {
        "attack_damage": 7,
        "health": 0,
        "defense": 0,
        "strength": 0,
        "intelligence": 0,
        "crit_chance": 0,
        "crit_damage": 0,
        "bonus_attack_speed": 0,
        "ability_damage": 0,
        "true_defence": 0,
        "ferocity": 0,
        "health_regen": 0,
        "vitality": 0,
        "mending": 0,
        "swing_range": 0,
        "rarity": "common",
        "enchant_types": [],
        "reforge_types": []
      }
  },
  {   "name": "Wooden Sword",
      "lore": "",
      "image": "Assets/textures/minecraft/wooden_sword.png",
      "stats": {
        "attack_damage": 7,
        "health": 0,
        "defense": 0,
        "strength": 0,
        "intelligence": 0,
        "crit_chance": 0,
        "crit_damage": 0,
        "bonus_attack_speed": 0,
        "ability_damage": 0,
        "true_defence": 0,
        "ferocity": 0,
        "health_regen": 0,
        "vitality": 0,
        "mending": 0,
        "swing_range": 0,
        "rarity": "common",
        "enchant_types": [],
        "reforge_types": []
      }
  },
  {   "name": "Iron Sword",
      "lore": "",
      "image": "Assets/textures/minecraft/iron_sword.png",
      "stats": {
        "attack_damage": 7,
        "health": 0,
        "defense": 0,
        "strength": 0,
        "intelligence": 0,
        "crit_chance": 0,
        "crit_damage": 0,
        "bonus_attack_speed": 0,
        "ability_damage": 0,
        "true_defence": 0,
        "ferocity": 0,
        "health_regen": 0,
        "vitality": 0,
        "mending": 0,
        "swing_range": 0,
        "rarity": "common",
        "enchant_types": [],
        "reforge_types": []
      }
  },
  {   "name": "Stone Sword",
      "lore": "",
      "image": "Assets/textures/minecraft/stone_sword.png",
      "stats": {
        "attack_damage": 7,
        "health": 0,
        "defense": 0,
        "strength": 0,
        "intelligence": 0,
        "crit_chance": 0,
        "crit_damage": 0,
        "bonus_attack_speed": 0,
        "ability_damage": 0,
        "true_defence": 0,
        "ferocity": 0,
        "health_regen": 0,
        "vitality": 0,
        "mending": 0,
        "swing_range": 0,
        "rarity": "common",
        "enchant_types": [],
        "reforge_types": []
      }
  },
  {   "name": "Golden Sword",
      "lore": "",
      "image": "Assets/textures/minecraft/golden_sword.png",
      "stats": {
        "attack_damage": 7,
        "health": 0,
        "defense": 0,
        "strength": 0,
        "intelligence": 0,
        "crit_chance": 0,
        "crit_damage": 0,
        "bonus_attack_speed": 0,
        "ability_damage": 0,
        "true_defence": 0,
        "ferocity": 0,
        "health_regen": 0,
        "vitality": 0,
        "mending": 0,
        "swing_range": 0,
        "rarity": "common",
        "enchant_types": [],
        "reforge_types": []
      }
  },
  {   "name": "Prismarine Blade",
      "lore": "",
      "image": "moos4/hypixel-hex.io/Assets/textures/minecraft/prismarine_blade.png",
      "stats": {
        "attack_damage": 7,
        "health": 0,
        "defense": 0,
        "strength": 0,
        "intelligence": 0,
        "crit_chance": 0,
        "crit_damage": 0,
        "bonus_attack_speed": 0,
        "ability_damage": 0,
        "true_defence": 0,
        "ferocity": 0,
        "health_regen": 0,
        "vitality": 0,
        "mending": 0,
        "swing_range": 0,
        "rarity": "common",
        "enchant_types": [],
        "reforge_types": []
      }
  }
]`

/*
base item

{   "name": "item",
      "lore": "itemLore",
      "image": "direction/to/img.png",
      "stats": {
        "attack_damage": 0,
        "health": 0,
        "defense": 0,
        "strength": 0,
        "intelligence": 0,
        "crit_chance": 0,
        "crit_damage": 0,
        "bonus_attack_speed": 0,
        "ability_damage": 0,
        "true_defence": 0,
        "ferocity": 0,
        "health_regen": 0,
        "vitality": 0,
        "mending": 0,
        "swing_range": 0,
        "rarity": "", // common, uncomon, rare, epic, legendary, mythic, divine, special, very special, ultimate, admin
        "enchant_types": [],
        "reforge_types": []
      }
  }
*/
